# Generated by Django 5.1.1 on 2024-10-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
