# Generated by Django 5.1.1 on 2024-09-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
