# Generated by Django 5.1.1 on 2024-10-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0006_rename_courses_college_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='city',
        ),
        migrations.RemoveField(
            model_name='college',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='nirfRank',
        ),
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
    ]
