# Generated by Django 5.1.1 on 2024-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0007_remove_college_city_remove_college_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='course_name',
            field=models.ManyToManyField(related_name='colleges', to='nexapp.course'),
        ),
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='college',
            name='nirfRank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
