# Generated by Django 5.1.1 on 2024-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0008_college_city_college_course_name_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
