# Generated by Django 5.1.1 on 2024-10-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0009_alter_college_city_alter_college_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
