# Generated by Django 5.1.1 on 2024-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nexapp', '0010_delete_college_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20)),
                ('application_type', models.CharField(max_length=20)),
                ('institute_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=10)),
                ('state', models.IntegerField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('govt', models.BooleanField(default=False)),
                ('program', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('intake', models.IntegerField(default=60)),
            ],
        ),
    ]
