# Generated by Django 5.1.1 on 2024-10-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
