# Generated by Django 5.1.1 on 2024-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0012_alter_college_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
