# Generated by Django 5.1.1 on 2024-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexapp', '0014_alter_college_city_alter_college_intake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='pincode',
            field=models.CharField(max_length=200),
        ),
    ]
